services:
  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile.production
    ports:
      - "4321:4321"
    env_file:
      - ./astro/.env.production
    depends_on:
      - drupal

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile.production
    ports:
      - "8081:8080"
      - "8444:8443"
    env_file:
      - ./drupal/.env.production
    volumes:
      - drupal_data:/bitnami/drupal
      - ./drupal/config:/config:ro
    depends_on:
      - mariadb

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    env_file:
      - ./.env.mariadb
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  drupal_data:
  mariadb_data: