services:
  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    env_file:
      - ./astro/.env.development
    volumes:
      - ./astro/src:/app/src:ro
      - ./astro/public:/app/public:ro
      - astro_node_modules:/app/node_modules
    depends_on:
      - drupal
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "8444:8443"
    env_file:
      - ./drupal/.env.development
    volumes:
      - drupal_data:/bitnami/drupal
      - ./drupal/config:/config:ro
      - ./drupal/scripts:/scripts:ro
    depends_on:
      - mariadb

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    env_file:
      - ./.env.mariadb
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  drupal_data:
  mariadb_data:
  astro_node_modules: