services:
  nginx:
    image: mirror.gcr.io/library/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      DOMAIN_SUFFIX: ${DOMAIN_SUFFIX}
    depends_on:
      - astro
      - drupal
      - minio

  astro:
    image: node:20-alpine
    working_dir: /app
    environment:
      DRUPAL_BASE_URL: http://drupal:8080
    volumes:
      - ./astro:/app
      - astro_node_modules:/app/node_modules
    depends_on:
      - drupal
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --allowed-hosts"

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT_NUMBER: 3306
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_NAME: drupal
      BITNAMI_DEBUG: true
      PHP_MEMORY_LIMIT: 256M
      # S3FS configuration
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: drupal-files
      S3_REGION: us-east-1
      S3_USE_HTTPS: "false"
      S3_HOSTNAME: minio:9000
      S3_USE_PATH_STYLE: "true"
      S3_PUBLIC_FOLDER: public
      S3_PRIVATE_FOLDER: private
      S3_USE_PRESIGNED_URLS: "true"
      S3_PRESIGNED_URL_LIFETIME: "180"
      S3_AS_DEFAULT_SCHEME: "true"
    volumes:
      - drupal_data:/bitnami/drupal
      - ./drupal/scripts:/scripts:ro
    depends_on:
      - mariadb
      - minio

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    environment:
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_DATABASE: drupal
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/bitnami/mariadb

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: drupal-files
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  drupal_data:
  mariadb_data:
  astro_node_modules:
  minio_data:
