services:
  nginx:
    image: mirror.gcr.io/library/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      DOMAIN_SUFFIX: ${DOMAIN_SUFFIX}
    depends_on:
      - astro
      - drupal
    restart: unless-stopped

  astro:
    build:
      context: ./astro
      dockerfile: Dockerfile.production
    environment:
      DRUPAL_BASE_URL: http://drupal:8080
      NODE_ENV: production
    depends_on:
      - drupal
    restart: unless-stopped

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_PORT_NUMBER: 3306
      DRUPAL_DATABASE_USER: ${DB_USER:-drupal}
      DRUPAL_DATABASE_PASSWORD: ${DB_PASSWORD:?Database password required}
      DRUPAL_DATABASE_NAME: ${DB_NAME:-drupal}
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT:?Hash salt required}
      BITNAMI_DEBUG: false
      PHP_MEMORY_LIMIT: 512M
      # S3 configuration - use real S3 or compatible service in production
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3 access key required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3 secret key required}
      S3_BUCKET: ${S3_BUCKET:-drupal-files}
      S3_REGION: ${S3_REGION:-us-east-1}
      S3_USE_HTTPS: ${S3_USE_HTTPS:-true}
      S3_HOSTNAME: ${S3_HOSTNAME:-s3.amazonaws.com}
      S3_USE_PATH_STYLE: ${S3_USE_PATH_STYLE:-false}
      S3_PUBLIC_FOLDER: ${S3_PUBLIC_FOLDER:-public}
      S3_PRIVATE_FOLDER: ${S3_PRIVATE_FOLDER:-private}
      S3_USE_PRESIGNED_URLS: ${S3_USE_PRESIGNED_URLS:-true}
      S3_PRESIGNED_URL_LIFETIME: ${S3_PRESIGNED_URL_LIFETIME:-180}
      S3_AS_DEFAULT_SCHEME: ${S3_AS_DEFAULT_SCHEME:-true}
    # Scripts are included in the image during build
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    environment:
      MARIADB_USER: ${DB_USER:-drupal}
      MARIADB_PASSWORD: ${DB_PASSWORD:?Database password required}
      MARIADB_DATABASE: ${DB_NAME:-drupal}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?Root password required}
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped

volumes:
  mariadb_data: