services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile.astro.prod
    ports:
      - "4321:4321"
    environment:
      - DRUPAL_BASE_URL=http://drupal:8080
    depends_on:
      - drupal

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "8444:8443"
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
      - DRUPAL_DATABASE_NAME=drupal
      - PHP_MEMORY_LIMIT=256M
    volumes:
      - drupal_data:/bitnami/drupal
      - ./config:/config:ro
    depends_on:
      - mariadb

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    environment:
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal
      - MARIADB_DATABASE=drupal
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  drupal_data:
  mariadb_data: