services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
      - "8444:8443"
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
      - DRUPAL_DATABASE_NAME=drupal
      - BITNAMI_DEBUG=true
      - PHP_MEMORY_LIMIT=256M
    volumes:
      - drupal_data:/bitnami/drupal
      - ./config:/config:ro
      - ./scripts:/scripts:ro
    depends_on:
      - mariadb

  mariadb:
    image: mirror.gcr.io/bitnami/mariadb:latest
    environment:
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal
      - MARIADB_DATABASE=drupal
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  drupal_data:
  mariadb_data: